export const HIGHEST_ZINDEX = 100000;
export const DEFAULT_ZINDEX = 0;
export const DRAGGABLE_ACTIVE_ZINDEX = 1000;

export const DEFAULT_FONT_SIZE = 14;
export const SMALLER_FONT_SIZE = DEFAULT_FONT_SIZE * 0.7143; //10
export const SMALL_FONT_SIZE = DEFAULT_FONT_SIZE * 0.857; //12
export const LARGE_FONT_SIZE = DEFAULT_FONT_SIZE * 1.143; //16
export const LARGER_FONT_SIZE = DEFAULT_FONT_SIZE * 1.4286; //20
export const TITLE_FONT_SIZE = DEFAULT_FONT_SIZE * 3.4286; //48
export const SUB_TITLE_FONT_SIZE = DEFAULT_FONT_SIZE * 2.2857; //32
